version: '2'
services:
  web:
    build: .
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      PRODUCTION: ${PRODUCTION}
      NODE_ENV: ${NODE_ENV}
  mongo:
    image: mongo:4.0.0-xenial
    ports:
      - "27017:27017"
